behaviors:
  ParkourAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.00094
      beta: 0.08912
      epsilon: 0.2114
      lambd: 0.94
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      network_type: lstm
      normalize: true
      hidden_units: 512
      num_layers: 5
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 194000000
    time_horizon: 512
    summary_freq: 10000
    threaded: false
    self_play:
    behavioral_cloning:

env_settings:
  num_envs: 7
  base_port: 5005

engine_settings:
  no_graphics: true
  time_scale: 3
